### ISSUE TITLE
How to import this project to eclipse ? 

### ISSUE THREAD

**Issue by codepython** [remibantos/jeeshop#38]

**Comment by muskacirca** [comment]
Import it via maven

**Comment by remibantos** [comment]
This project has not been released yet. At this time, you can fork it to suit your need, and import in with eclipse maven integration as per @muskacirca comment.

When released, you'll be able to add jeeshop maven dependencies directly to your own project as Jeeshop 1.0 alpha release artifacts will be pushed to maven central repository.
We are still working to deliver this first release very soon. 

Remaining tasks/issues are listed in (jeeshop-1.0-alpha)[https://github.com/remibantos/jeeshop/milestones/jeeshop-1.0-alpha] milestone. Don't hesitate to comment them if you have any remark, or participate by doing a pull request.

**Comment by msldiarra** [comment]
;-)
